version: '3.8'

services:
  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgresql" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 20s
